modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="prehistoricfauna" #mandatory
version="2.2.0" #mandatory
displayName="Prehistoric Fauna" #mandatory
credits="AGSuko, Antlion, Bastion, Baular, Coda, Corgi Taco, Obsolerus, RafaMv, Ralof, Seal, superlord9362, Weastian" #optional
authors="superlord9362, Corgi Taco, RafaMv, AlexThe668" #optional
description='''
Travel to the past to discover worlds time forgot. Bring back animals long extinct, or join their world.
'''
[[dependencies.prehistoricfauna]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.prehistoricfauna]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
